name: Build Halo Shop Plugin

on:
  push:
    paths:
      - 'halo-shop-plugin/**'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'halo-shop-plugin/**'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B -f halo-shop-plugin/pom.xml clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: halo-shop-plugin-jar
          path: halo-shop-plugin/target/*.jar
